### PR TITLE
Update structure for Metanorma

### PR DESCRIPTION
**Pull request by ronaldtse**
### Metanorma PR checklist

 - [ ] Breaking changes (list related PRs)
 - [ ] Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] Gem with native library introduced

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP Which GH Action do I use for a normal document that needs to be built (not tested on ubuntu, macos, etc)? Could you help update the workflow here? Thanks!

**Comment by ronaldtse** [comment]
@CAMOBAP please feel free to merge when it passes! (also we don't need the ubuntu/windows/macos builds). Thanks!

**Comment by CAMOBAP** [comment]
Done

**Review by CAMOBAP — COMMENTED** [review]
LGTM

**Pull request merged**
