### PR TITLE
Markup corrections

### PR DESCRIPTION
**Pull request by anermina**
As requested in https://github.com/metanorma/ogc-citygml2/issues/3.

### CODE REVIEW

**Comment by manuelfuenmayor** [comment]
Thanks @anermina!
I'm about to push a few corrections more.

**Comment by manuelfuenmayor** [comment]
@anermina, I've changed this approach `___text__`  to `&#95;__text__`, because there are cases where unwanted italic text is introduced. 
For example:

*Original:*
issue1_original

*Markup:*
````
The geometry model of GML3 consists of primitives, which may be combined to form complexes, composite geometries or aggregates. For each dimension, there is a geometrical primitive: a zero-dimensional object is a _Point_, a one-dimensional a 
___Curve__, a two-dimensional a ___Surface__, and a three-dimensional a ___Solid__ (<<fig_9>>). Each geometry can have its 
own coordinate reference system. A solid is bounded by surfaces and a surface by curves. In CityGML, a curve is restricted to be 
a straight line, thus only the GML3 class _LineString_ is used. Surfaces in CityGML are represented by _Polygons_, which define a 
planar geometry, i.e. the boundary and all interior points are required to be located in one single plane.
````

*Generated:*
issue1_generated

**Comment by ronaldtse** [comment]
@anermina @manuel489 thank you. I think it would be better to treat these UML objects as source code rather than italics, especially since they include the `_` underscore. The italics mechanism in AsciiDoc doesn't work that well.

**Review by ronaldtse — APPROVED** [review]

**Comment by manuelfuenmayor** [comment]
> I think it would be better to treat these UML objects as source code rather than italics, especially since they include the _ underscore. The italics mechanism in AsciiDoc doesn't work that well.

@ronaldtse, the current approach (described above) works fine despite the underscore mechanism.
Are you sure you want to make this change?

**Comment by ronaldtse** [comment]
@manuel489 let's merge this first. This document will actually be given for Japanese translation, so I cannot know whether the Japanese editor would be able to handle this rather complex syntax.

**Pull request merged**
